"""
tests for tools/monitor.py.

    python tools/tests/monitor.py

Three things are checked, and the first is the reason this file exists.

THE THIRD IMPLEMENTATION HAS TO AGREE WITH THE FIRST
    monitor.py decodes OHW1 for the third time in this repository — after
    protocol.js, which is the specification, and hw_proto.c, which is what the
    board runs. Three independent copies are deliberate, and the deal is that
    the CRC catches a divergence immediately. That is only true if somebody
    checks, so the vectors below are generated by running the real encoder out
    of protocol.js rather than written down here. Frames copied into this file
    by hand would prove that monitor.py agrees with whoever typed them.

THE RULES WITH NO HARDWARE BEHIND THEM
    The line bound and the boot accounting are ordinary code. A rule that can
    only be exercised with a board attached is one nobody exercises, which is
    how the monitor would come to be trusted without ever having been right.

THE VERDICT IS THE PRODUCT
    Telling a board that restarted from a board that went quiet is the whole
    job. It is worth more than one assertion.
"""

import importlib.util
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PROTOCOL_JS = ROOT / 'frontend' / 'js' / 'link' / 'protocol.js'

spec = importlib.util.spec_from_file_location('monitor', ROOT / 'tools' / 'monitor.py')
monitor = importlib.util.module_from_spec(spec)
spec.loader.exec_module(monitor)

passed = failed = skipped = 0


def ok(name, cond, detail=''):
    global passed, failed
    if cond:
        passed += 1
        print('  PASS  ' + name)
    else:
        failed += 1
        print('  FAIL  ' + name + (('  — ' + str(detail)) if detail else ''))


def skip(name, why):
    global skipped
    skipped += 1
    print('  SKIP  %s — %s' % (name, why))


# ---------------------------------------------------------------------------
# 1. agreement with the specification
# ---------------------------------------------------------------------------

# Every case is a shape the wire actually carries, plus the three that have
# caught real divergences before: a payload containing the frame terminator, a
# payload outside ASCII, and a chunk at full width.
CASES = """
[
  { "t": "hello", "proto": 1, "fw": "0.11.0", "sha": "e8bcc63f9260f958",
    "slot": "factory", "board": "esp32s3_generic", "mac": "3C:84:27:AB:CD:EF",
    "boot_id": "5abc1234", "reset": "BROWNOUT", "provisioned": false, "ssid": "",
    "psram": 8388608, "flash": 8388608, "heap": 300000, "heap_total": 390000,
    "temp_crit_c": 85, "rx": 0, "temp_c": 32.5 },
  { "t": "beat", "uptime_s": 12.75, "heap_free": 299184, "psram_free": 8380416,
    "psram_largest": 8257536, "cpu_mhz": 240, "boot_id": "5abc1234" },
  { "t": "status", "stage": "camera_absent", "detail": "ESP_ERR_NOT_SUPPORTED" },
  { "t": "status", "stage": "quoted", "detail": "a literal \\" *ABCD\\" inside a string" },
  { "t": "status", "stage": "wide", "detail": "32.5 \\u00b0C on the die, ss\\u00efd \\u00e9\\u00e8" },
  { "t": "img", "seq": 7, "w": 800, "h": 600, "q": 12, "bytes": 4096, "chunks": 9 },
  { "t": "ping" }
]
"""

GENERATOR = """
import { encodeFrame, crc16 } from %s;
const cases = JSON.parse(%s);
console.log(JSON.stringify({
  frames: cases.map(c => ({ obj: c, line: encodeFrame(c).replace(/\\n$/, '') })),
  malformed: (() => { const b = '{"t":"ping",}';
    return `#OHW1 ${b} *${crc16(b).toString(16).toUpperCase().padStart(4, '0')}`; })(),
}));
"""


def vectors():
    """
    Framed lines produced by the real encoder, or None if node is absent.

    The cases travel inside the script rather than as an argument, and the
    script is pure ASCII because json.dumps escapes everything above it. A
    Windows console hands argv to a child in the active code page, which
    replaces every character the page cannot represent — so the degree sign
    that this check exists to exercise would arrive as a question mark and the
    two implementations would be compared on a payload neither would ever see.
    """
    script = GENERATOR % (json.dumps(PROTOCOL_JS.as_uri()), json.dumps(CASES))
    try:
        out = subprocess.run(
            [_node(), '--input-type=module', '-e', script],
            capture_output=True, encoding='utf-8', timeout=60)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    return json.loads(out.stdout)


def _node():
    return 'node.exe' if sys.platform == 'win32' else 'node'


def check_against_spec():
    # The published check value, first. A CRC that fails this is wrong in a way
    # no round-trip against another implementation would reveal, because both
    # could be wrong together.
    ok('crc16("123456789") is 0x29B1', monitor.crc16(b'123456789') == 0x29B1,
       hex(monitor.crc16(b'123456789')))

    v = vectors()
    if v is None:
        skip('frames from protocol.js round-trip',
             'node is not available, so the specification could not be run')
        return

    for case in v['frames']:
        frame, reason = monitor.decode_line(case['line'])
        ok('round-trips a %s frame' % case['obj']['t'],
           frame == case['obj'] and reason is None, (frame, reason))

    # Length is checked separately: a generator that silently produced nothing
    # would otherwise pass this section by asserting nothing at all.
    ok('every case was exercised', len(v['frames']) == 7, len(v['frames']))

    line = v['frames'][0]['line']
    ok('a corrupted body fails its CRC',
       monitor.decode_line(line[:20] + 'x' + line[21:])[1] == 'crc')
    ok('a frame with no CRC suffix is refused',
       monitor.decode_line(line[:line.rfind(' *')])[1] == 'no-crc-suffix')
    ok('a valid CRC over malformed JSON is reported as JSON, not corruption',
       monitor.decode_line(v['malformed'])[1] == 'json')

    # The property the sentinel exists for. ESP-IDF log output shares this
    # endpoint, and mistaking it for a damaged frame would report a fault on
    # every boot.
    frame, reason = monitor.decode_line('I (312) harness: openhardware 0.11.0')
    ok('log output is neither a frame nor an error', frame is None and reason is None, reason)


# ---------------------------------------------------------------------------
# 2. the line bound
# ---------------------------------------------------------------------------

def check_line_reader():
    r = monitor.LineReader()
    ok('a line split across reads is assembled once',
       r.push('#OHW1 par') == [] and r.push('t\nrest') == ['#OHW1 part'])

    r = monitor.LineReader()
    ok('carriage returns do not survive', r.push('one\r\ntwo\r\n') == ['one', 'two'])
    ok('and empty lines are not passed on', monitor.LineReader().push('\n\n\na\n') == ['a'])

    # One bad line costs one bad line. The frames queued behind it must still
    # arrive, or a single burst of noise would take a whole image with it.
    r = monitor.LineReader(limit=32)
    r.push('x' * 40)
    ok('an overlong line is counted', r.dropped == 1, r.dropped)
    got = r.push('tail-of-the-bad-line\nkept\n')
    ok('its remainder is discarded and the reader resynchronises', got == ['kept'], got)
    ok('and the buffer did not keep growing', len(r.buf) == 0, len(r.buf))

    r = monitor.LineReader()
    r.push('half a line with no newline')
    r.reset()
    ok('a board leaving the bus takes its half-line with it', r.push('whole\n') == ['whole'])


# ---------------------------------------------------------------------------
# 3. reboot, or a stalled wire
# ---------------------------------------------------------------------------

class Recorder:
    """Stands in for the terminal, so what was said can be asserted on."""

    def __init__(self):
        self.lines = []

    def line(self, kind, text):
        self.lines.append((kind, text))

    def said(self, needle):
        return any(needle in text for _, text in self.lines)


class Clock:
    def __init__(self):
        self.t = 1000.0

    def __call__(self):
        return self.t


def watch():
    rec = Recorder()
    clock = Clock()
    return monitor.Watch(rec, clock=clock), rec, clock


def check_reboot():
    w, rec, clock = watch()

    w.frame({'t': 'hello', 'boot_id': 'aaaa1111', 'reset': 'POWERON', 'fw': '0.11.0'})
    for i in range(4):
        clock.t += 0.25
        w.frame({'t': 'beat', 'uptime_s': 0.5 + i * 0.25, 'boot_id': 'aaaa1111'})
    ok('one boot while the board keeps reporting', len(w.boots) == 1, len(w.boots))

    # Gone for four seconds, and back with an uptime shorter than the gap. That
    # is the signature of a restart and nothing else produces it.
    clock.t += 4.0
    w.tick()
    ok('silence is put on the record', rec.said('no telemetry'))

    w.frame({'t': 'hello', 'boot_id': 'bbbb2222', 'reset': 'BROWNOUT', 'fw': '0.11.0'})
    ok('a fresh boot_id is a second boot', len(w.boots) == 2, len(w.boots))
    ok('and the reset reason is carried through', w.boots[1]['reset'] == 'BROWNOUT')
    ok('the previous boot is recorded with how long it lasted',
       abs(w.boots[0]['lasted'] - 1.25) < 1e-9, w.boots[0]['lasted'])

    w.summary()
    ok('the summary states it was a restart', rec.said('It is not a transmit stall'))
    ok('and names the reason', rec.said('BROWNOUT'))


def check_reboot_without_hello():
    """A missed identity frame must not lose a boot."""
    w, rec, clock = watch()

    w.frame({'t': 'hello', 'boot_id': 'aaaa1111', 'reset': 'POWERON'})
    clock.t += 0.25
    w.frame({'t': 'beat', 'uptime_s': 8.0, 'boot_id': 'aaaa1111'})
    clock.t += 0.25
    w.frame({'t': 'beat', 'uptime_s': 0.4, 'boot_id': 'aaaa1111'})

    ok('uptime going backwards is a boot even with no hello', len(w.boots) == 2, len(w.boots))
    ok('and it says how it was noticed', rec.said('uptime went backwards'))


def check_stall():
    """The other half of the question, and the answer that is easy to miss."""
    w, rec, clock = watch()

    w.frame({'t': 'hello', 'boot_id': 'aaaa1111', 'reset': 'POWERON'})
    clock.t += 0.25
    w.frame({'t': 'beat', 'uptime_s': 10.0, 'boot_id': 'aaaa1111'})

    clock.t += 4.0
    w.tick()
    # Back with an uptime that ran straight through the gap. The board never
    # stopped; something between it and here did.
    w.frame({'t': 'beat', 'uptime_s': 14.0, 'boot_id': 'aaaa1111'})

    ok('a gap the uptime ran through is not a boot', len(w.boots) == 1, len(w.boots))
    ok('and it is named as a stall', rec.said('the transmit path stalled'))

    w.summary()
    ok('the summary refuses to call it a restart',
       rec.said('uptime never went backwards') and not rec.said('It is not a transmit stall'))


def check_attached_mid_session():
    """
    A board already running announces itself every five seconds, so the first
    frame the monitor sees is usually a beat.
    """
    w, rec, clock = watch()

    clock.t += 0.25
    w.frame({'t': 'beat', 'uptime_s': 402.5, 'boot_id': 'cccc3333'})
    ok('a beat before any hello still registers the boot', len(w.boots) == 1, len(w.boots))
    ok('and no reset reason is invented for it', w.boots[0]['reset'] is None)
    ok('the banner says how the boot was noticed', rec.said('attached mid-session'))

    clock.t += 0.25
    w.frame({'t': 'beat', 'uptime_s': 402.75, 'boot_id': 'cccc3333'})
    w.summary()
    ok('and the summary counts one boot, not two', rec.said('1 boot,'))


def check_beats_without_a_boot_id():
    """Older firmware, or a frame shape this build has never seen."""
    w, rec, clock = watch()

    clock.t += 0.25
    w.frame({'t': 'beat', 'uptime_s': 12.0})
    w.summary()
    ok('beats with no boot_id are not counted as a boot', len(w.boots) == 0, len(w.boots))
    ok('and the summary declines to answer rather than guessing',
       rec.said('nothing here can tell a restart from a stall'))
    ok('it does not claim one boot it never saw', not rec.said('One boot, uptime never'))


def check_says_nothing_it_did_not_see():
    """Absence is drawn, not hidden — the rule the rest of the project follows."""
    w, rec, _ = watch()
    w.summary()
    ok('a board that said nothing is reported as exactly that',
       rec.said('No beats arrived at all'))
    ok('and no verdict is offered about why',
       not rec.said('transmit path') and not rec.said('restarted'))


# ---------------------------------------------------------------------------

print('\n  monitor\n')
check_against_spec()
check_line_reader()
check_reboot()
check_reboot_without_hello()
check_stall()
check_attached_mid_session()
check_beats_without_a_boot_id()
check_says_nothing_it_did_not_see()

print('\n  %d passed, %d failed%s\n'
      % (passed, failed, ', %d skipped' % skipped if skipped else ''))
sys.exit(1 if failed else 0)
