#!/usr/bin/env python3
"""Loopback build service for agent-written OpenHardware applications."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
HARNESS = ROOT / "firmware" / "harness"
APP_DIR = HARNESS / "components" / "app"
DEFAULT_APP_DIR = ROOT / "firmware" / "apps" / "default"
DRAFT_DIR = ROOT / "firmware" / "workspace" / "app"
ARTIFACTS = ROOT / "firmware" / "artifacts"
BASELINE = ROOT / "firmware" / "baseline"
API_FILE = HARNESS / "components" / "hw_app_api" / "include" / "hw_app.h"
DIST = ROOT / "firmware" / "dist"
VERSION_FILE = HARNESS / "version.txt"
APP_CMAKE_SOURCES = APP_DIR / "app_sources.cmake"
IDF_IMAGE = "espressif/idf:v5.3"
BUILD_VOLUME = "openhardware-build"

NAME_RE = re.compile(r"^[a-z0-9_]+\.(?:c|h)$")


def remove_tree(path: Path) -> None:
    """Remove a directory on a filesystem that says no the first time.

    The same retry tools/baseline.py needs, and for the same reason: a synced
    folder holds files open for moments at a time and marks some of them
    read-only, and either answer makes rmtree raise on Windows. Clearing the
    attribute and trying again a few times is what it takes.
    """
    def clear(func, target, _exc):
        os.chmod(target, stat.S_IWRITE)
        func(target)

    for attempt in range(5):
        try:
            shutil.rmtree(path, onerror=clear)
            return
        except OSError:
            if attempt == 4:
                raise
            time.sleep(0.2)
FORBIDDEN_I2C_RE = re.compile(r"i2c_master\.h|i2c_new_master_bus|i2c_master_")
DIAGNOSTIC_RE = re.compile(
    r"^(.+?):(\d+):(\d+): (fatal error|error|warning|note): (.*)$"
)
LINK_ERROR_RE = re.compile(r"undefined reference to [`']([^`']+)[`']")
CMAKE_ERROR_RE = re.compile(r"^CMake Error at (.+?):(\d+) \([^)]*\):$")
APP_INFO_RE = re.compile(
    r"\.name\s*=\s*\"([^\"]*)\".*?\.version\s*=\s*\"([^\"]*)\"",
    re.DOTALL,
)

LADDER = ["QQVGA", "QVGA", "CIF", "HVGA", "VGA", "SVGA", "XGA", "HD", "SXGA", "UXGA"]


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat().replace("+00:00", "Z")


def bash_path() -> str:
    override = os.environ.get("OHW_BASH")
    if override:
        return override
    git_bash = Path(r"C:\Program Files\Git\bin\bash.exe")
    return str(git_bash) if git_bash.exists() else "bash"


def run_command(command: list[str], cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        errors="replace",
        check=False,
    )


def source_sha(files: dict[str, str]) -> str:
    digest = hashlib.sha256()
    for name in sorted(files):
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(files[name].encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def app_identity(files: dict[str, str]) -> tuple[str, str]:
    match = APP_INFO_RE.search(files.get("app.c", ""))
    return match.groups() if match else ("unknown", "unknown")


def validate_files(value) -> tuple[dict[str, str] | None, str | None]:
    if not isinstance(value, dict):
        return None, "files must be an object"
    if "app.c" not in value:
        return None, "files must include app.c"
    if len(value) > 32:
        return None, "an app may contain at most 32 files"

    clean: dict[str, str] = {}
    for name, content in value.items():
        if not isinstance(name, str) or not NAME_RE.fullmatch(name):
            return None, "file names must match [a-z0-9_]+.(c|h)"
        if not isinstance(content, str):
            return None, f"{name} must contain text"
        if len(content.encode("utf-8")) > 256 * 1024:
            return None, f"{name} is larger than 256 KB"
        if FORBIDDEN_I2C_RE.search(content):
            return None, (
                f"{name} uses the new I2C API, which cannot be linked beside "
                "the camera's legacy driver on ESP-IDF 5.3"
            )
        clean[name] = content
    return clean, None


def app_manifest(files: dict[str, str]) -> str:
    """Render the generated source list without exposing the component manifest."""
    sources = "\n".join(f'    "{name}"' for name in sorted(files) if name.endswith(".c"))
    return f'''# Generated by tools/buildd.py; application requests cannot replace this file.
set(APP_SRCS
{sources}
)
'''


def source_files(directory: Path) -> dict[str, str]:
    files = {}
    if not directory.exists():
        return files
    for path in sorted(directory.iterdir()):
        if path.is_file() and path.suffix in (".c", ".h"):
            files[path.name] = path.read_text(encoding="utf-8")
    return files


def replace_sources(files: dict[str, str]) -> None:
    """Replace the mutable draft and mirror it into the compiler scratch tree."""
    DRAFT_DIR.mkdir(parents=True, exist_ok=True)
    previous = DRAFT_DIR / ".previous"
    previous.mkdir(parents=True, exist_ok=True)

    for old in previous.iterdir():
        if old.is_file() and old.suffix in (".c", ".h"):
            old.unlink()
    for old in DRAFT_DIR.iterdir():
        if old.is_file() and old.suffix in (".c", ".h"):
            shutil.copy2(old, previous / old.name)
    for old in DRAFT_DIR.iterdir():
        if old.is_file() and old.suffix in (".c", ".h"):
            old.unlink()
    for name, content in files.items():
        (DRAFT_DIR / name).write_text(content, encoding="utf-8", newline="\n")
    write_scratch(files)


def write_scratch(files: dict[str, str]) -> None:
    """Mirror one source set into the ESP-IDF component used for compilation."""
    for old in APP_DIR.iterdir():
        if old.is_file() and old.suffix in (".c", ".h"):
            old.unlink()
    for name, content in files.items():
        (APP_DIR / name).write_text(content, encoding="utf-8", newline="\n")
    # Changing the explicit manifest makes Ninja rerun CMake when a source is
    # added or removed. CONFIGURE_DEPENDS cannot be used because ESP-IDF also
    # evaluates component manifests in a restricted CMake script-mode pass.
    APP_CMAKE_SOURCES.write_text(app_manifest(files), encoding="utf-8", newline="\n")


def parse_diagnostics(log: str) -> list[dict]:
    found = []
    seen = set()
    lines = log.splitlines()
    for index, line in enumerate(lines):
        match = DIAGNOSTIC_RE.match(line.strip())
        if match:
            file_name, row, col, severity, message = match.groups()
            if file_name.startswith("/project/"):
                file_name = str(HARNESS / file_name[len("/project/"):])
            item = {
                "file": file_name,
                "line": int(row),
                "col": int(col),
                "severity": severity,
                "message": message,
            }
        else:
            cmake = CMAKE_ERROR_RE.match(line.strip())
            if cmake:
                message = "CMake configuration failed"
                for following in lines[index + 1:index + 8]:
                    candidate = following.strip()
                    if candidate and candidate != "Call Stack (most recent call first):":
                        message = candidate
                        break
                item = {
                    "file": cmake.group(1),
                    "line": int(cmake.group(2)),
                    "col": 0,
                    "severity": "error",
                    "message": message,
                }
                key = tuple(item.values())
                if key not in seen:
                    seen.add(key)
                    found.append(item)
                continue
            link = LINK_ERROR_RE.search(line)
            if not link:
                continue
            item = {
                "file": "",
                "line": 0,
                "col": 0,
                "severity": "error",
                "message": f"undefined reference to {link.group(1)}",
            }
        key = tuple(item.values())
        if key not in seen:
            seen.add(key)
            found.append(item)
    return found


def read_sources() -> dict[str, str]:
    draft = source_files(DRAFT_DIR)
    return draft or source_files(APP_DIR)


def partition_offsets() -> dict[str, int]:
    offsets = {}
    for raw in (HARNESS / "partitions.csv").read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        cols = [part.strip() for part in line.split(",")]
        if len(cols) >= 4 and cols[0] in ("factory", "ota_0", "ota_1"):
            offsets[cols[0]] = int(cols[3], 0)
    return offsets


def candidate_document(build_id: str, manifest: dict, app: dict, *, activation_protocol: int = 0) -> dict:
    application = next((part for part in manifest.get("parts", []) if part.get("role") == "application"), None)
    if not application:
        application = next((part for part in manifest.get("parts", []) if part.get("path", "").endswith(".bin") and part.get("offset") == partition_offsets().get("factory")), None)
    if not application:
        raise ValueError("the package contains no application image")

    return {
        **manifest,
        "kind": "candidate",
        "build_id": build_id,
        "app": app,
        "activation_protocol": activation_protocol,
        "targets": {key: value for key, value in partition_offsets().items() if key.startswith("ota_")},
        "total_bytes": application["size"],
        "parts": [{**application, "role": "application"}],
    }


def publish_candidate(build_id: str, manifest: dict, app: dict, files: dict[str, str], note: str) -> tuple[Path, dict]:
    """Copy one finished build to a path no later build will rewrite."""
    candidate = candidate_document(build_id, manifest, app, activation_protocol=2)

    artifact = ARTIFACTS / build_id
    if artifact.exists():
        raise ValueError(f"artifact {build_id} already exists")
    shutil.copytree(DIST, artifact)
    source_dir = artifact / "source"
    source_dir.mkdir()
    for name, content in files.items():
        (source_dir / name).write_text(content, encoding="utf-8", newline="\n")

    (artifact / "manifest.json").write_text(
        json.dumps(candidate, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    (artifact / "app.json").write_text(
        json.dumps({**app, "files": sorted(files), "builtAt": utc_now(), "note": note}, indent=2) + "\n",
        encoding="utf-8", newline="\n",
    )
    return artifact, candidate


class Builds:
    def __init__(self, runner=run_command):
        self.runner = runner
        self.lock = threading.Lock()
        self.records: dict[str, dict] = {}
        self.order: list[str] = []
        self.busy = False
        self._load_artifacts()

    def _load_artifacts(self):
        if not ARTIFACTS.exists():
            return
        loaded = []
        for directory in ARTIFACTS.iterdir():
            if not directory.is_dir() or not re.fullmatch(r"[a-z0-9]+", directory.name):
                continue
            try:
                record_path = directory / "record.json"
                if record_path.exists():
                    record = json.loads(record_path.read_text(encoding="utf-8"))
                else:
                    manifest = json.loads((directory / "manifest.json").read_text(encoding="utf-8"))
                    app = json.loads((directory / "app.json").read_text(encoding="utf-8"))
                    if manifest.get("kind") != "candidate":
                        manifest = candidate_document(directory.name, manifest, app)
                        (directory / "manifest.json").write_text(
                            json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n"
                        )
                    record = {
                        "id": directory.name,
                        "status": "built",
                        "startedAt": app.get("builtAt"),
                        "endedAt": app.get("builtAt"),
                        "log": [], "diagnostics": [], "note": app.get("note", ""),
                        "app": {key: app.get(key) for key in ("name", "version", "sha")},
                        "image": {
                            "kind": manifest.get("kind", "candidate"),
                            "build_id": directory.name,
                            "artifact": f"/firmware/artifacts/{directory.name}/",
                            "version": manifest.get("version"),
                            "elf_sha8": manifest.get("elf_sha8"),
                            "total_bytes": manifest.get("total_bytes"),
                            "parts": manifest.get("parts", []),
                            "targets": manifest.get("targets", {}),
                            "activation_protocol": manifest.get("activation_protocol", 0),
                        },
                    }
                loaded.append(record)
            except (OSError, ValueError, TypeError):
                continue
        loaded.sort(key=lambda record: record.get("startedAt") or "")
        for record in loaded:
            build_id = record.get("id")
            if build_id:
                self.records[build_id] = record
                self.order.append(build_id)

    def latest(self):
        with self.lock:
            return self.records.get(self.order[-1]) if self.order else None

    def list(self):
        with self.lock:
            return [self.records[key] for key in reversed(self.order[-20:])]

    def get(self, build_id: str):
        with self.lock:
            return self.records.get(build_id)

    def remove(self, build_id: str):
        """Forget one build and delete what it left on disk.

        A candidate is immutable, so removing it is the only way it ever
        changes; the record and the artifact go together, because a record
        pointing at images that are gone is worse than neither. A build that
        is still compiling is refused rather than removed out from under the
        compiler.
        """
        with self.lock:
            record = self.records.get(build_id)
            if not record:
                return {"ok": False, "error": "build not found", "status": 404}
            if record.get("status") == "building":
                return {"ok": False, "error": "that build is still running", "status": 409}
            self.records.pop(build_id, None)
            if build_id in self.order:
                self.order.remove(build_id)

        directory = ARTIFACTS / build_id
        try:
            if directory.exists():
                remove_tree(directory)
        except OSError as error:
            # The record is already gone, so the page will not offer it again.
            # What is left on disk is reported rather than hidden.
            return {"ok": True, "id": build_id, "warning": f"some files could not be deleted: {error}"}
        return {"ok": True, "id": build_id}

    def start(self, files: dict[str, str], note: str = "", clean: bool = False):
        with self.lock:
            if self.busy:
                return None
            replace_sources(files)
            build_id = uuid.uuid4().hex[:12]
            name, version = app_identity(files)
            record = {
                "id": build_id,
                "status": "building",
                "startedAt": utc_now(),
                "endedAt": None,
                "log": [],
                "diagnostics": [],
                "image": None,
                "app": {
                    "name": name,
                    "version": version,
                    "sha": source_sha(files),
                },
                "note": note,
            }
            self.records[build_id] = record
            self.order.append(build_id)
            self.busy = True

        threading.Thread(
            target=self._run,
            args=(build_id, files, note, clean),
            name=f"build-{build_id}",
            daemon=True,
        ).start()
        return record

    def _call(self, command: list[str]):
        result = self.runner(command, ROOT)
        if isinstance(result, tuple):
            return int(result[0]), str(result[1])
        return int(result.returncode), str(result.stdout or "")

    def _finish(self, build_id: str, status: str, log: str, diagnostics: list, image=None):
        with self.lock:
            record = self.records[build_id]
            record["status"] = status
            record["endedAt"] = utc_now()
            record["log"] = log.splitlines()[-200:]
            record["diagnostics"] = diagnostics
            record["image"] = image
            self.busy = False
            artifact = ARTIFACTS / build_id
            if artifact.exists():
                (artifact / "record.json").write_text(
                    json.dumps(record, indent=2) + "\n", encoding="utf-8", newline="\n"
                )

    def _run(self, build_id: str, files: dict[str, str], note: str, clean: bool):
        log_parts = []
        build_cmd = [bash_path(), "tools/build.sh"]
        if clean:
            build_cmd.append("--clean")
        code, output = self._call(build_cmd)
        log_parts.append(output)
        if code != 0:
            log = "\n".join(log_parts)
            self._finish(build_id, "failed", log, parse_diagnostics(log))
            return

        nm_cmd = [
            bash_path(), "-lc",
            "MSYS_NO_PATHCONV=1 docker run --rm "
            f"-v {BUILD_VOLUME}:/build:ro {IDF_IMAGE} "
            "xtensa-esp32s3-elf-nm /build/openhardware_harness.elf",
        ]
        nm_code, nm_output = self._call(nm_cmd)
        log_parts.append(nm_output)
        if nm_code != 0:
            diagnostic = {
                "file": "", "line": 0, "col": 0, "severity": "error",
                "message": "the final ELF could not be inspected for the incompatible new I2C driver",
            }
            self._finish(build_id, "failed", "\n".join(log_parts), [diagnostic])
            return
        if re.search(r"(?m)^\S+\s+T\s+i2c_acquire_bus_handle$", nm_output):
            diagnostic = {
                "file": "", "line": 0, "col": 0, "severity": "error",
                "message": (
                    "the application linked the incompatible new I2C driver "
                    "(i2c_acquire_bus_handle); the image was not published"
                ),
            }
            self._finish(build_id, "failed", "\n".join(log_parts), [diagnostic])
            return

        package_code, package_output = self._call([bash_path(), "tools/package.sh"])
        log_parts.append(package_output)
        log = "\n".join(log_parts)
        if package_code != 0:
            self._finish(build_id, "failed", log, parse_diagnostics(log))
            return

        try:
            manifest = json.loads((DIST / "manifest.json").read_text(encoding="utf-8"))
            app = self.records[build_id]["app"]
            artifact, candidate = publish_candidate(build_id, manifest, app, files, note)
            image = {
                "kind": "candidate",
                "build_id": build_id,
                "artifact": f"/firmware/artifacts/{build_id}/",
                "version": candidate.get("version"),
                "elf_sha8": candidate.get("elf_sha8"),
                "total_bytes": candidate.get("total_bytes"),
                "parts": candidate.get("parts", []),
                "targets": candidate.get("targets", {}),
                "activation_protocol": candidate.get("activation_protocol", 0),
            }
        except (OSError, ValueError, TypeError) as error:
            diagnostic = {
                "file": "", "line": 0, "col": 0, "severity": "error",
                "message": f"the packaged image metadata could not be read: {error}",
            }
            self._finish(build_id, "failed", log, [diagnostic])
            return

        self._finish(build_id, "built", log, parse_diagnostics(log), image=image)


BUILDS = Builds()


def allowed_origin(origin: str | None) -> str:
    fallback = os.environ.get("OHW_PAGE_ORIGIN", "http://localhost:8000")
    if not origin:
        return fallback
    try:
        parsed = urlparse(origin)
        if parsed.scheme in ("http", "https") and parsed.hostname in ("localhost", "127.0.0.1", "::1"):
            return origin
    except ValueError:
        pass
    return fallback


class Handler(BaseHTTPRequestHandler):
    server_version = "OpenHardwareBuild/1"

    def log_message(self, fmt, *args):
        print("buildd:", fmt % args)

    def cors(self):
        self.send_header("Access-Control-Allow-Origin", allowed_origin(self.headers.get("Origin")))
        self.send_header("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Vary", "Origin")

    def send_json(self, status: int, value):
        body = json.dumps(value, separators=(",", ":")).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.cors()
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.cors()
        self.end_headers()

    def do_GET(self):
        path = urlparse(self.path).path
        if path == "/health":
            latest = BUILDS.latest()
            self.send_json(200, {
                "ok": True,
                "docker": shutil.which("docker") is not None,
                "busy": BUILDS.busy,
                "harnessVersion": VERSION_FILE.read_text(encoding="utf-8").strip(),
                "baselineReady": (BASELINE / "manifest.json").exists(),
                "artifacts": len(BUILDS.order),
                "lastBuild": latest,
            })
            return
        if path == "/app":
            self.send_json(200, {
                "api": API_FILE.read_text(encoding="utf-8"),
                "files": read_sources(),
                "baseline": source_files(DEFAULT_APP_DIR),
                "ladder": LADDER,
            })
            return
        if path == "/baseline":
            manifest_path = BASELINE / "manifest.json"
            if not manifest_path.exists():
                self.send_json(404, {"ok": False, "error": "the baseline image has not been built yet; stop buildd and run python tools/baseline.py"})
                return
            self.send_json(200, json.loads(manifest_path.read_text(encoding="utf-8")))
            return
        if path == "/builds":
            self.send_json(200, {"builds": BUILDS.list()})
            return
        match = re.fullmatch(r"/build/([a-z0-9]+)", path)
        if match:
            record = BUILDS.get(match.group(1))
            self.send_json(200 if record else 404, record or {"ok": False, "error": "build not found"})
            return
        match = re.fullmatch(r"/source/([a-z0-9]+)", path)
        if match:
            directory = ARTIFACTS / match.group(1) / "source"
            files = source_files(directory)
            self.send_json(200 if files else 404, {"files": files} if files else {"ok": False, "error": "artifact source not found"})
            return
        self.send_json(404, {"ok": False, "error": "not found"})

    def do_DELETE(self):
        """Remove one build: its record and the images and source it left.

        Only a person reaches this — the page's own menu — because it destroys
        the one copy of a candidate that exists. No tool calls it: an agent
        that could delete the artefact it just built could erase the evidence
        of what it flashed.
        """
        match = re.fullmatch(r"/build/([a-z0-9]+)", urlparse(self.path).path)
        if not match:
            self.send_json(404, {"ok": False, "error": "not found"})
            return
        result = BUILDS.remove(match.group(1))
        self.send_json(result.pop("status", 200), result)

    def do_POST(self):
        if urlparse(self.path).path != "/build":
            self.send_json(404, {"ok": False, "error": "not found"})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            if length <= 0 or length > 9 * 1024 * 1024:
                raise ValueError("request body is empty or too large")
            request = json.loads(self.rfile.read(length).decode("utf-8"))
        except (ValueError, UnicodeDecodeError, json.JSONDecodeError) as error:
            self.send_json(400, {"ok": False, "error": str(error)})
            return

        files, error = validate_files(request.get("files") if isinstance(request, dict) else None)
        if error:
            self.send_json(400, {"ok": False, "error": error})
            return
        note = request.get("note", "")
        if not isinstance(note, str):
            self.send_json(400, {"ok": False, "error": "note must be text"})
            return
        record = BUILDS.start(files, note=note[:1000], clean=bool(request.get("clean")))
        if not record:
            self.send_json(409, {"ok": False, "error": "a build is already running"})
            return
        self.send_json(202, {"id": record["id"], "status": "building"})


def main():
    parser = argparse.ArgumentParser(description="Build OpenHardware app firmware on loopback.")
    parser.add_argument("--port", type=int, default=int(os.environ.get("OHW_BUILDD_PORT", "8001")))
    args = parser.parse_args()
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"OpenHardware build daemon: http://127.0.0.1:{args.port}")
    print(f"Application sources: {APP_DIR}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
